CREATE TABLE ERS_REIMBURSEMENT_STATUS (
	REIMB_STATUS_ID SERIAL PRIMARY KEY,
	REIMB_STATUS VARCHAR(10)
);
CREATE TABLE ERS_REIMBURSEMENT_TYPE (
	REIMB_TYPE_ID SERIAL PRIMARY KEY,
	REIMB_TYPE VARCHAR(10)
);
CREATE TABLE ERS_USER_ROLE (
	ERS_USER_ROLE_ID SERIAL PRIMARY KEY,
	USER_ROLE VARCHAR(10)
);
CREATE TABLE ERS_USERS (
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(150) UNIQUE NOT NULL,
	USER_ROLE_ID INT NOT NULL,
	FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLE(ERS_USER_ROLE_ID) ON DELETE CASCADE
);
CREATE TABLE ERS_REIMBURSEMENT (
	REIMB_ID serial PRIMARY KEY,
	REIMB_AMOUNT DOUBLE PRECISION ,
	REIMB_SUBMITTED TIMESTAMP,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_AUTHOR INT NOT NULL,
	REIMB_RESOLVER INT ,
	REIMB_STATUS_ID INT NOT NULL,
	REIMB_TYPE_ID INT NOT NULL,
	FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID) ON DELETE CASCADE,
	FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID) ON DELETE CASCADE,
	FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID) ON DELETE CASCADE,
	FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID) ON DELETE CASCADE
);


